"""Report generation tool – produces PPTX, HTML, and Markdown artefacts."""

from __future__ import annotations

import json
import logging
import os
from pathlib import Path

from jinja2 import Template
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN

import config
from models.schemas import ReportOutput, ReportSection

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Jinja2 HTML template (embedded to keep the project self-contained)
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{{ title }}</title>
<style>
  :root { --primary: #1a365d; --accent: #2b6cb0; --bg: #f7fafc; --text: #2d3748; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: 'Segoe UI', system-ui, sans-serif; color: var(--text);
         background: var(--bg); line-height: 1.7; padding: 2rem; }
  .container { max-width: 900px; margin: auto; background: #fff;
               border-radius: 12px; box-shadow: 0 4px 24px rgba(0,0,0,.08);
               padding: 3rem; }
  h1 { color: var(--primary); font-size: 2rem; border-bottom: 3px solid var(--accent);
       padding-bottom: .5rem; margin-bottom: .25rem; }
  .subtitle { color: var(--accent); font-size: 1.1rem; margin-bottom: 2rem; }
  h2 { color: var(--primary); margin-top: 2rem; margin-bottom: .75rem; font-size: 1.35rem; }
  p  { margin-bottom: 1rem; }
  ul { margin-left: 1.5rem; margin-bottom: 1rem; }
  li { margin-bottom: .35rem; }
  .footer { margin-top: 3rem; text-align: center; font-size: .85rem; color: #a0aec0; }
</style>
</head>
<body>
<div class="container">
  <h1>{{ title }}</h1>
  {% if subtitle %}<p class="subtitle">{{ subtitle }}</p>{% endif %}
  {% for section in sections %}
  <h2>{{ section.heading }}</h2>
  <p>{{ section.content }}</p>
  {% if section.bullet_points %}
  <ul>
    {% for bp in section.bullet_points %}<li>{{ bp }}</li>
    {% endfor %}
  </ul>
  {% endif %}
  {% endfor %}
  <div class="footer">Generated by Agentic Analysis &amp; Reporting App</div>
</div>
</body>
</html>
""")


class ReportGeneratorTool:
    """Generates report artefacts (PPTX, HTML, Markdown) from structured data."""

    name: str = "generate_report"
    description: str = (
        "Generate presentation and report files from structured report data. "
        "Produces PowerPoint (.pptx), HTML, and Markdown files."
    )

    parameters_schema: dict = {
        "type": "object",
        "properties": {
            "report_json": {
                "type": "string",
                "description": (
                    "JSON string matching the ReportOutput schema with keys: "
                    "title, subtitle, sections (each with heading, content, bullet_points)."
                ),
            },
        },
        "required": ["report_json"],
    }

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def run(self, report_json: str) -> dict:
        """Parse *report_json* and generate all output files.

        Returns a dict with keys: files (list of paths), error.
        """
        try:
            data = json.loads(report_json)
            report = ReportOutput(**data)
        except Exception as exc:
            logger.error("Failed to parse report JSON: %s", exc)
            return {"files": [], "error": f"Invalid report JSON: {exc}"}

        os.makedirs(config.OUTPUT_DIR, exist_ok=True)
        safe_name = self._safe_filename(report.title)
        generated: list[str] = []

        generated.append(self._write_pptx(report, safe_name))
        generated.append(self._write_html(report, safe_name))
        generated.append(self._write_markdown(report, safe_name))

        report.generated_files = generated
        logger.info("Generated report files: %s", generated)
        return {"files": generated, "error": None}

    # ------------------------------------------------------------------
    # PowerPoint generation
    # ------------------------------------------------------------------

    def _write_pptx(self, report: ReportOutput, safe_name: str) -> str:
        path = os.path.join(config.OUTPUT_DIR, f"{safe_name}.pptx")
        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        # --- Title slide ---
        slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(slide_layout)
        slide.shapes.title.text = report.title
        if slide.placeholders[1]:
            slide.placeholders[1].text = report.subtitle

        # --- Content slides ---
        for section in report.sections:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = section.heading

            body_shape = slide.placeholders[1]
            tf = body_shape.text_frame
            tf.word_wrap = True

            # Section prose
            p = tf.paragraphs[0]
            p.text = section.content
            p.font.size = Pt(16)
            p.alignment = PP_ALIGN.LEFT

            # Bullet points
            for bp in section.bullet_points:
                p = tf.add_paragraph()
                p.text = bp
                p.font.size = Pt(14)
                p.level = 1

        # --- Closing slide ---
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = "Thank You"
        if slide.placeholders[1]:
            slide.placeholders[1].text = "Generated by Agentic Analysis & Reporting App"

        prs.save(path)
        logger.info("PPTX saved to %s", path)
        return path

    # ------------------------------------------------------------------
    # HTML generation
    # ------------------------------------------------------------------

    def _write_html(self, report: ReportOutput, safe_name: str) -> str:
        path = os.path.join(config.OUTPUT_DIR, f"{safe_name}.html")
        html = _HTML_TEMPLATE.render(
            title=report.title,
            subtitle=report.subtitle,
            sections=[s.model_dump() for s in report.sections],
        )
        Path(path).write_text(html, encoding="utf-8")
        logger.info("HTML saved to %s", path)
        return path

    # ------------------------------------------------------------------
    # Markdown generation
    # ------------------------------------------------------------------

    def _write_markdown(self, report: ReportOutput, safe_name: str) -> str:
        path = os.path.join(config.OUTPUT_DIR, f"{safe_name}.md")
        lines: list[str] = [f"# {report.title}\n"]
        if report.subtitle:
            lines.append(f"*{report.subtitle}*\n")

        for section in report.sections:
            lines.append(f"\n## {section.heading}\n")
            lines.append(f"{section.content}\n")
            for bp in section.bullet_points:
                lines.append(f"- {bp}")
            lines.append("")

        lines.append("\n---\n*Generated by Agentic Analysis & Reporting App*\n")
        Path(path).write_text("\n".join(lines), encoding="utf-8")
        logger.info("Markdown saved to %s", path)
        return path

    # ------------------------------------------------------------------
    @staticmethod
    def _safe_filename(name: str) -> str:
        """Convert an arbitrary title into a filesystem-safe slug."""
        import re
        slug = re.sub(r"[^\w\s-]", "", name.lower())
        return re.sub(r"[\s-]+", "_", slug).strip("_")[:80]
