"""Report generation for research findings."""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from pathlib import Path

from research_agent.config import REPORTS_DIR


@dataclass
class ResearchReport:
    """Structured research report."""

    query: str
    sections: list[ReportSection] = field(default_factory=list)
    generated_at: str = field(
        default_factory=lambda: datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )

    def add_section(self, title: str, content: str) -> None:
        self.sections.append(ReportSection(title=title, content=content))

    def to_markdown(self) -> str:
        lines = [
            f"# Research Report: {self.query}",
            f"*Generated on {self.generated_at}*",
            "",
            "---",
            "",
        ]
        for section in self.sections:
            lines.append(f"## {section.title}")
            lines.append("")
            lines.append(section.content)
            lines.append("")

        lines.append("---")
        lines.append("*Report generated by Research Agent v1.0*")
        return "\n".join(lines)

    def save(self, filename: str | None = None) -> Path:
        """Save report to the research_reports directory."""
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        if filename is None:
            safe_query = "".join(
                c if c.isalnum() or c in " -_" else "_" for c in self.query
            )[:60]
            ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{ts}_{safe_query}.md"
        path = REPORTS_DIR / filename
        path.write_text(self.to_markdown())
        return path


@dataclass
class ReportSection:
    title: str
    content: str
